### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by cekkec** [jimmy-dq/SimVOS#2]
Hi! It's an honor to see your paper, and thank you for your new contribution in Video object segmentation. I wanted to use your method, so I'm building an experimental environment and I'm going to ask you a few questions!

How long did your training time take in **SimVOS-B** and **SimVOS-R** respectively? And is there a big difference in performance in an environment where you use 4 GPUs for 8?

**Comment by jimmy-dq** [comment]
> Hi! It's an honor to see your paper, and thank you for your new contribution in Video object segmentation. I wanted to use your method, so I'm building an experimental environment and I'm going to ask you a few questions!
> 
> How long did your training time take in **SimVOS-B** and **SimVOS-R** respectively? And is there a big difference in performance in an environment where you use 4 GPUs for 8?

Thanks for your interests. The single stage training (Youtube+DAVIS) takes about 10+ hours (A100 GPUs) by using SimVOS-B and SimVOS-R . Sorry that I do not remember the exact training time, welcome for reporting the training time :) 
I think 4 GPUs should be fine if you keep the total training batch size as the same with 8 GPUs.

**Comment by cekkec** [comment]
![image](https://github.com/jimmy-dq/SimVOS/assets/78406960/7e139dfe-9c5a-4ac1-8e36-0e2df0d867d9)
Thank you for your quick response! I read your paper carefully and found that you expressed it kindly, but I missed it.
I want to train your model with the RTX 3090 now but you trained using 8 A100 GPUs so I don't know what will happen in my environment! I just wanted to ask if you used all the GPUs with full memory.
And when I checked the uploaded code, it is confirmed that the valid code is only for DAVIS, can I get a code for YouTube19(or 18)?
I really want to prove my method using your model as baseline!

**Comment by cekkec** [comment]
I tried running your code(in SimVOS/model/models_vit.py), but I got an error in the code below!
![image](https://github.com/jimmy-dq/SimVOS/assets/78406960/e89b1219-0a91-49a7-b895-37e7192bfba1)
`x = self.patch_embed(frames, is_template=True)`
`TypeError: forward() got an unexpected keyword argument 'is_template'`

So when I removed the 'is_template' factor, the following error occurred
`assert H == self.img_size[0] and W == self.img_size[1], \
AssertionError: Input image size (384*384) doesn't match model (224*224).`

The training code was executed as follows:
`python -m torch.distributed.run\
    --master_port 12120 \
    --nproc_per_node=2\
    train_simvos.py\
    --davis_root /data2/local_datasets/NNN/N_DAVIS/GTEAD_N10\
    --yv_root /data2/local_datasets/NNN/N_YouTube/GTEAD_Y_N10\
    --id XMem_CEDIIN_N10_d0.0001_i1_bg\
    --load_network /data/cekkec/SimVOS/pretrained_models/mae_pretrain_vit_base.pth \
    --stage 3\
    --layer_index 4\
    --use_token_learner False`

    I'd really appreciate it if you could tell me how to solve this problem! Thank you!

**Comment by yahooo-m** [comment]
I guess the patch_embed in timm has been changed. Please provide the changed code.

**Comment by jimmy-dq** [comment]
> I tried running your code(in SimVOS/model/models_vit.py), but I got an error in the code below! ![image](https://private-user-images.githubusercontent.com/78406960/304759142-e89b1219-0a91-49a7-b895-37e7192bfba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTM1MTQsIm5iZiI6MTcxMzk1MzIxNCwicGF0aCI6Ii83ODQwNjk2MC8zMDQ3NTkxNDItZTg5YjEyMTktMGE5MS00OWE3LWI4OTUtMzdlNzE5MmJmYmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEwMDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MTQ1M2Y5OGE3MzRjNzk2YzBiMDFkZjQyNjViZThlYWUxNGMzNTBiNTZiNWQ0ZTFjNGE0MThmZmFlZGQxN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ukd3gxO5pXuQzPvgVBtJjKuX70I8t1wmjsh58riD39c) `x = self.patch_embed(frames, is_template=True)` `TypeError: forward() got an unexpected keyword argument 'is_template'`
> 
> So when I removed the 'is_template' factor, the following error occurred `assert H == self.img_size[0] and W == self.img_size[1], \ AssertionError: Input image size (384*384) doesn't match model (224*224).`
> 
> The training code was executed as follows: `python -m torch.distributed.run\ --master_port 12120 \ --nproc_per_node=2\ train_simvos.py\ --davis_root /data2/local_datasets/NNN/N_DAVIS/GTEAD_N10\ --yv_root /data2/local_datasets/NNN/N_YouTube/GTEAD_Y_N10\ --id XMem_CEDIIN_N10_d0.0001_i1_bg\ --load_network /data/cekkec/SimVOS/pretrained_models/mae_pretrain_vit_base.pth \ --stage 3\ --layer_index 4\ --use_token_learner False`
> 
> ```
> I'd really appreciate it if you could tell me how to solve this problem! Thank you!
> ```

Hi, this is because the default image size constraint (224) in the 3rd party timm package. You could modify the vision_transformer.py (L164) of timm and comment the constraint (assert) lines.

**Comment by jimmy-dq** [comment]
> I guess the patch_embed in timm has been changed. Please provide the changed code.

Yes, that's true.
