### ISSUE TITLE
Can you provide training code on single GPU for windows or ubuntu?

### ISSUE THREAD

**Issue by Fo4me** [jimmy-dq/SimVOS#3]
Very good work!
It bothers me a lot to realize that I only have multi-GPU distributed training when I run training. I hope to learn from your achievements on limited device!
Looking forward to your reply!

**Comment by jimmy-dq** [comment]
> Very good work! It bothers me a lot to realize that I only have multi-GPU distributed training when I run training. I hope to learn from your achievements on limited device! Looking forward to your reply!

Hi, thanks for your interests. Training w/ single GPU is time-consuming. Maybe you could use our default VOS models and do some fine-tuning. For Windows, it should work as well as Ubuntu, since there is no specific installed packages in our work.
