### ISSUE TITLE
  is_template in patch_embed/mask_patch_embed

### ISSUE THREAD

**Issue by DeepTag** [jimmy-dq/SimVOS#5]
Dear author,

In the functions patch_embed/mask_patch_embed in models_vit.py, there is a param is_template. I believe this param is added by yourself. Could you please provide  the implementation of these two functions with this is_template param?

Thanks!

**Comment by jimmy-dq** [comment]
Hi, thanks for pointing out this. Yes, it is a typo, we modify the 3rd party patch_embed implementation in our original implementation. To fix this, just simply  removing the `is_template` param.
